# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='eid',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='node',
            name='eid',
            field=models.CharField(max_length=2),
        ),
    ]
